# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='그룹')),
                ('type', models.SmallIntegerField(choices=[(0, '가족'), (1, '친구'), (2, '회사'), (3, '스타'), (4, '연인')], verbose_name='종류')),
                ('link', models.TextField(max_length=400, verbose_name='링크')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '그룹장'), (1, '그룹원')], verbose_name='권한')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routine.Group', verbose_name='그룹')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField(verbose_name='순서')),
                ('type', models.SmallIntegerField(choices=[(0, '자동차'), (1, '비행기')], verbose_name='종류')),
                ('departure', models.TextField(max_length=100, verbose_name='출발지')),
                ('departureTime', models.DateTimeField(verbose_name='출발 시간')),
                ('arrival', models.TextField(max_length=100, verbose_name='도착지')),
                ('arrivalTime', models.DateTimeField(verbose_name='도착 시간')),
                ('distance', models.IntegerField(verbose_name='거리')),
                ('flight_no', models.TextField(null=True, verbose_name='편명')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.SmallIntegerField(choices=[(0, 'Personal'), (1, 'Business')], verbose_name='목적')),
                ('type', models.SmallIntegerField(choices=[(0, '편도'), (1, '왕복')], verbose_name='종류')),
                ('departure', models.TextField(max_length=30, verbose_name='출발지')),
                ('departureTime', models.DateTimeField(verbose_name='출발 시간')),
                ('arrival', models.TextField(max_length=30, verbose_name='도착지')),
                ('arrivalTime', models.DateTimeField(verbose_name='도착 시간')),
                ('realTimeLocation', models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0, verbose_name='GPS')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Group', verbose_name='그룹')),
                ('registrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routine.Schedule'),
        ),
    ]
