# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='API 이름')),
                ('desc', models.TextField(verbose_name='설명')),
                ('useYN', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
        ),
        migrations.CreateModel(
            name='ApiHeader',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='키')),
                ('valueType', models.SmallIntegerField(choices=[(0, '텍스트'), (1, '숫자'), (2, 'Bool'), (99, 'Token')], verbose_name='값 종류')),
                ('value', models.TextField(verbose_name='값')),
                ('memo', models.TextField(verbose_name='메모')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
            options={
                'verbose_name': 'API 헤더',
                'verbose_name_plural': 'API 헤더',
            },
        ),
        migrations.CreateModel(
            name='ApiService',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='이름')),
                ('desc', models.TextField(verbose_name='설명')),
                ('useYN', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('resType', models.SmallIntegerField(choices=[(0, 'JSON'), (1, 'XML')], default=0, help_text='응답하는 형식에 따라 데이터 변환을 해준다', verbose_name='응답형식')),
                ('reqMethod', models.SmallIntegerField(choices=[(0, 'GET'), (1, 'POST')], default=0, verbose_name='요청 형식')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
            options={
                'verbose_name': 'API 서비스',
                'verbose_name_plural': 'API 서비스',
            },
        ),
        migrations.CreateModel(
            name='ApiServiceParams',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='키')),
                ('valueType', models.SmallIntegerField(choices=[(0, '텍스트'), (1, '숫자'), (2, 'Bool'), (99, 'Token')], verbose_name='값 종류')),
                ('valueInputType', models.SmallIntegerField(choices=[(0, '사용자 직접 입력'), (1, '입력값')], verbose_name='값 입력 방식')),
                ('value', models.TextField(verbose_name='값')),
                ('reqMethod', models.SmallIntegerField(choices=[(0, 'GET'), (1, 'POST')], default=0, verbose_name='요청 형식')),
                ('memo', models.TextField(verbose_name='메모')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApiService')),
            ],
            options={
                'verbose_name': 'API 서비스 파라미터',
                'verbose_name_plural': 'API 서비스 파라미터',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useYN', models.BooleanField(choices=[(True, '사용'), (False, '미사용')], verbose_name='사용여부')),
                ('name', models.TextField(max_length=100, verbose_name='이름')),
                ('isDev', models.BooleanField(choices=[(True, 'Dev'), (False, 'Real')], default=False, verbose_name='종류')),
                ('token', models.TextField(max_length=500, verbose_name='토큰')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('expiredDate', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
            options={
                'verbose_name': 'API 토큰',
                'verbose_name_plural': 'API 토큰',
            },
        ),
    ]
