# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apiconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Dev'), (1, 'Real')])),
                ('token', models.TextField(max_length=500)),
                ('remark', models.TextField(blank=True, null=True)),
                ('expiredDate', models.DateField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2017, 7, 8, 3, 49, 46, 111134, tzinfo=utc))),
            ],
        ),
    ]
