# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': 'API', 'verbose_name_plural': 'API'},
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='desc',
            field=models.TextField(verbose_name='서비스명'),
        ),
        migrations.AlterField(
            model_name='apiservice',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='서비스 ID'),
        ),
    ]
