# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170708_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfig',
            options={'verbose_name': 'API 설정', 'verbose_name_plural': 'API 설정'},
        ),
    ]
