# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170708_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='expiredDate',
            field=models.DateField(blank=True, null=True, verbose_name='만료일'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='name',
            field=models.TextField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='기타'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='token',
            field=models.TextField(max_length=500, verbose_name='토큰'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='type',
            field=models.IntegerField(choices=[(0, 'Dev'), (1, 'Real')], verbose_name='종류'),
        ),
    ]
