# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170713_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='useYN',
            field=models.BooleanField(default=True, verbose_name='사용여부'),
        ),
    ]
