# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, verbose_name='FCM 토큰')),
                ('useYN', models.BooleanField(default=True, verbose_name='알림 허용')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'FCM 토큰',
                'verbose_name_plural': 'FCM 토큰',
            },
        ),
        migrations.CreateModel(
            name='FcmMessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentData', models.TextField(verbose_name='전송 데이터')),
                ('sentDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='전송 날짜')),
                ('resultMsg', models.TextField(verbose_name='결과 메세지')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm.Fcm', verbose_name='수신자')),
            ],
            options={
                'verbose_name': 'FCM 히스토리',
                'verbose_name_plural': 'FCM 히스토리',
            },
        ),
    ]
